//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATMSimulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardDetail
    {
        public string UserName { get; set; }
        public string CardNumber { get; set; }
        public string ExpiryDate { get; set; }
        public string Pin { get; set; }
        public string Cvv { get; set; }
    }
}
